### ISSUE TITLE
Option to set ascii to TRUE or NA in internal calls to saveRDS

### ISSUE THREAD

**Issue by wlandau** [richfitz/storr#48]
Would this help caches play nicer with version control?

**Comment by richfitz** [comment]
I'm not sure actually.  I suspect that compression will be a bigger issue (because small changes in the input will result in arbitrarily large changes in the output).

But at the same time, things like git - despite popular belief - does not store differences but instead stores complete files so I don't think that there will be much space saving.  Later on when it packs files there might be something gained from this.

If you can show that there is a tangible benefit then I can expose it in the same way as the other RDS calls (done [here](https://github.com/richfitz/storr/blob/master/R/driver_rds.R#L124-L127) and with a default that matches existing storrs.  Getting the backwards compatibility is a bit of a trick so I'd rather not add the complexity unless it really helps.

**Comment by richfitz** [comment]
Having looked more into the serialisation format I'm certain this will not help
