### ISSUE TITLE
Generate a flat log that plays nicely with version control.

### ISSUE THREAD

**Issue by wlandau-lilly** [richfitz/storr#66]
@noamross suggested this yesterday. From @jennybc's [screenshot](https://cloud.githubusercontent.com/assets/599454/21154917/fd96e5c6-c124-11e6-8cd4-de955f426a39.png) in #37, some `storr`s do not play nicely with version control. For `storr_rds()` caches, a mob of tiny cryptically-named files mangles commit logs and histories.

```r
library(storr)
cache <- storr_rds("cache", mangle_key = TRUE)
cache$set("dataset", mtcars)
cache$set("model", lm(mpg ~ cyl, data = mtcars))
cache$set("model", "2018-01-16", namespace = "date")
```

```sh
git init
git add cache/
git status

## ...
## new file:   cache/config/compress
## new file:   cache/config/hash_algorithm
## new file:   cache/config/mangle_key
## new file:   cache/config/mangle_key_pad
## new file:   cache/config/version
## new file:   cache/data/16fd1c5df9d87bf77cf26f98c8fc3e2d.rds
## new file:   cache/data/a63c70e73b58d0823ab3bcbd3b543d6f.rds
## new file:   cache/data/f643ea09200af5263b29892f211faea1.rds
## new file:   cache/keys/date/bW9kZWw
## new file:   cache/keys/objects/ZGF0YXNldA
## new file:   cache/keys/objects/bW9kZWw
```

What if we use a single flat log to represent the state of the cache?

```r
storr_hash_log <- function(cache){
  out <- NULL
  for(namespace in cache$list_namespaces()){
    tmp <- lapply(
      X = cache$list(namespace = namespace),
      FUN = single_hash_log,
      namespace = namespace,
      cache = cache
    )
    out <- rbind(out, do.call(rbind, tmp))
  }
  out
}

single_hash_log <- function(key, namespace, cache){
  data.frame(
    hash = cache$get_hash(key = key, namespace = namespace),
    key = key,
    namespace = namespace,
    stringsAsFactors = FALSE
  )
}

hash_log <- storr_hash_log(cache)
hash_log

##                               hash     key namespace
## 1 f643ea09200af5263b29892f211faea1   model      date
## 2 a63c70e73b58d0823ab3bcbd3b543d6f dataset   objects
## 3 16fd1c5df9d87bf77cf26f98c8fc3e2d   model   objects
```

At any point, the user could just save a version-control-friendly hash log and easily track changes to the cache itself.

```r
write.table(
  x = hash_log,
  file = "hash_log.txt",
  quote = FALSE,
  row.names = FALSE
)
```

Similar functionality is in [drake_cache_log()](https://wlandau-lilly.github.io/drake/reference/drake_cache_log.html), [drake_cache_log_file()](https://wlandau-lilly.github.io/drake/reference/drake_cache_log_file.html), and `drake::make(..., cache_log_file = TRUE)`.

**Comment by richfitz** [comment]
So the intention here is for something that is run only periodically?  To save a description of the keys in a storr?  But not the "source of truth" for a storr?  Then from a version control point of view one would version control the data directory, gitignore the keys directory and periodically export this index.

One would also want the inverse I presume that would set the keys to match an import (what do do here when a key references unknown data? what to do with existing keys?).  Otherwise there's not a great deal of point saving this file under version control.

**Comment by wlandau-lilly** [comment]
Yes, I think it would run periodically. And I guess there is enough information there to get the keys back from the log. I had not thought about the feature this way.

For me (and presumably @noamross) the point is to have human-readable commit histories. If you have code that automatically generates a `storr_rds()`, a log would help track how the database changes as the code changes. This could be really important for reproducibility in general. Right now, there is a huge lack of tools that do data versioning, and `git` + `storr` + `storr_hash_log()` could help meet the need.

**Comment by noamross** [comment]
The half-formed application of this I was imagining was using it to avoid re-creating storr objects that are otherwise available (e.g., files that are otherwise saved in version control).  So while this wouldn't be be run all the time by **storr**, a system built on top of **storr** (such as **drake** or other versioning/build systems), would use it regularly, at every build or possibly in a pre-commit hook.

**Comment by richfitz** [comment]
Can you please take a look at the [`i66_index`](https://github.com/richfitz/storr/tree/i66_index) branch and see how close that gets you.  The methods are `$index_export()` and `$index_import()`.  There is no support for doing the saving to file as I imagine that the application might want control over that (and adding it complicates return types)

**Comment by wlandau-lilly** [comment]
I tinkered with both methods, and they seem to work great. Thanks, Rich!

**Comment by wlandau** [comment]
See also #71.
