### ISSUE TITLE
Add a .gitignore file inside RDS storrs

### ISSUE THREAD

**Issue by wlandau** [richfitz/storr#71]
Similar to https://github.com/ropensci/drake/commit/10c7a3ceecf20a5ba2729551dad83fd89cc2048c. With a `.gitignore` file with "*" inside the cache folder, we can prevent the mob of tiny cryptically-named files from clogging up version control. maybe a `storr_rds(gitignore = TRUE)`? Would you support this as the default behavior?

**Comment by richfitz** [comment]
I don't think so sorry - this is something that I think is more naturally kept at the application level.  In drake, you know if the files are worth saving or not but I would not want to exclude files from git by default because if that happens and someone _loses_ data it's worse than someone having an out-of-control git repo.  And for ignoring it, I feel that anyone using git and caring about what is in their git repo is in the position to curate their own gitignore files (I don't appreciate tools pre-empting me on this personally).

But thanks for the suggestion!
